[package]
name = "datafusion"
description = "DataFusion is a datasource-agnostic distributed query processing framework for Rust inspired by Apache Spark"
version = "0.1.6"
authors = ["Andy Grove <andygrove73@gmail.com>"]
homepage = "https://datafusion.rs"
keywords = [ "distributed", "query", "data", "processing", "spark" ]
repository = "https://github.com/andygrove/datafusion-rs"
license = "Apache-2.0"

[lib]
name = "datafusion"
path = "src/lib.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[[bin]]
name = "console"
path = "src/bin/console/main.rs"

[dependencies]
csv = "1.0.0-beta.5"
futures = "0.1.18"
futures-timer = "0.1"
tokio-core = "0.1.2"
hyper = "0.11.2"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
rprompt = "1.0"
etcd = "0.8.0"
clap = "2.29.4"
uuid = { version = "0.6.0-beta", features = ["v5"] }

[dev-dependencies]
criterion = "0.2.0"

[[bench]]
name = "dataframe_bench"
harness = false

[[bench]]
name = "sql_bench"
harness = false
