[package]
name = "datafusion"
description = "DataFusion is a datasource-agnostic distributed query processing framework for Rust inspired by Apache Spark"
version = "0.1.1"
authors = ["Andy Grove <andygrove73@gmail.com>", "bgardner@squarelabs.net"]
homepage = "https://datafusion.rs"
keywords = [ "distributed", "query", "data", "processing", "spark" ]
repository = "https://github.com/andygrove/datafusion-rs"
license = "Apache-2.0"

[lib]
name = "datafusion"
path = "src/lib.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[dependencies]
csv = "1.0.0-beta.5"
futures = "0.1.14"
hyper = "0.11.2"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
#etcd = "0.8.0"
